### ISSUE TITLE
instead of command line can you make it through csv or html?

### ISSUE THREAD

**Issue by princebhatia09** [evcsec/overseer#10]

**Comment by princebhatia09** [comment]
![image](https://user-images.githubusercontent.com/34816200/57137822-96128f00-6dce-11e9-8bb8-2f0644f10300.png)

**Comment by evcsec** [comment]
Ideally the whole tool would be GUI-driven through some HTML, CSS and most likely Python. This will happen over time as we mature the tool.

The screenshot provided looks like the chromedriver or gecko driver hasn't been specified in the configuration file (system.ini). An example of this configuration looks like this (please note this is on MacOS):

```
[Visual]
driver_type = chrome
driver_location = /Applications/ChromeDriver
```
Where `driver_location` refers to the pathway to the file on the OS.

**Comment by evcsec** [comment]
We have added CSV data input on our vision of deliverables in the future.
I'm going to close this off for now, but please feel free to open new issues if the above did not assist.

Cheers
