### ISSUE TITLE
Please add some screenshots and how to use it?

### ISSUE THREAD

**Issue by princebhatia09** [evcsec/overseer#9]
Please add some screenshots and how to use it?

**Comment by evcsec** [comment]
Hey @princebhatia09, thanks for your message and interest in the tool.
I'll be adding some screenshots, sample config files and some other useful information over the coming days.

**Comment by evcsec** [comment]
Added some sample configuration files to help (#12). 
Screenshots will be coming in a subsequent update.

**Comment by evcsec** [comment]
Screenshots and updated readme have been completed to allow easier setup (#13).
Thanks for your suggestions 👍
